version: '3.7'

services:
  n1:
    hostname: n1
    container_name: n1
    image: cassandra:3.11
    networks:
      - cluster
    environment:
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
  n2:
    hostname: n2
    container_name: n2
    image: cassandra:3.11
    networks:
      - cluster
    environment:
      - CASSANDRA_SEEDS=n1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK2

  n3:
    hostname: n3
    container_name: n3
    image: cassandra:3.11
    networks:
      - cluster
    environment:
      - CASSANDRA_SEEDS=n1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK3


networks:
  cluster:
